# Ref. http://stackoverflow.com/a/8817519/5496185
detachAllPackages <- function() {
  
  basic.packages <- c("package:grid","package:parallel","package:splines","package:stats","package:graphics","package:grDevices","package:utils","package:datasets","package:methods","package:base")
  
  package.list <- search()[ifelse(unlist(gregexpr("package:",search()))==1,TRUE,FALSE)]
  
  package.list <- setdiff(package.list,basic.packages)
  
  if (length(package.list)>0)  for (package in package.list) detach(package, character.only=TRUE)
}

#library(SnowballC)
strNum <- data.frame(ltr = c('zero', 'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten', 'eleven', 'twelve', 'thirteen', 'fourteen', 'fifteen', 'sixteen', 'seventeen', 'eighteen', 'nineteen', 'twenty', 'thirty', 'forty', 'fifty', 'sixty', 'seventy', 'eighty', 'ninety'), 
                     num = c("0","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","2","3","4","5","6","7","8","9"))

# Clean up the data

# substitute numbers
sub_num <- function(w, strNum) {
  strNum <- as.data.frame(strNum)
  words <- unlist(strsplit(w, " "))
  nwords <- words
  for(i in 1:length(words)) {
    if(length(strNum[strNum$ltr == words[i], "num"]) > 0)
      
      tryCatch(nwords[i] <- as.character(strNum[strNum$ltr == words[i], "num"]),
               warning=function(w) {
                 cat("problem values: ", words[i], "result: ", as.character(strNum[strNum$ltr == words[i], "num"]), "\n")
               }
      )
      
  }
  return(nwords)
}

str_normalize <- function(s, x=1){
  
  if(x %% 100 == 0) cat(paste0(x , " values normalized. \n"))
  
  if(!is.na(s) && is.character(s)) {
    
    s <- gsub("(\\w)\\.([A-Z])", "\\1 \\2", s) #Split words with a.A
    s = tolower(s)
    s = gsub("  ", " ", s)
    s = gsub(",", "", s) # could be number / segment later
    s = gsub("\\$", " ", s)
    s = gsub("\\?", " ", s)
    s = gsub("-", " ", s)
    s = gsub("//", "/", s)
    s = gsub("\\.\\.", ".", s)
    #s = gsub(" / ", " ", s)
    s = gsub(" \\ ", " ", s)
    s = gsub("\\.", " . ", s)
    
    s = gsub("(^\\.|/)([a-z])", "", s)      # remove "." or "/" from the beginning.
    s = gsub("(^/)", "", s)
    s = gsub("(\\.|/)$", "", s)             # remove "." or "/" from the end. 
    s = gsub("([0-9])( *)/( *)([0-9])", "\\1/\\4", s)
    
    # s = paste(sub_num(s, strNum), collapse = " ")
    s = str_num_normalize(s)
    
    s = gsub("([0-9])([a-z])", "\\1 \\2", s)
    s = gsub("([a-z])([0-9])", "\\1 \\2", s)
    s = gsub("([a-z])( *)\\.( *)([a-z])", "\\1 \\4", s)
    s = gsub("([a-z])( *)/( *)([a-z])", "\\1 \\4", s)
    s = gsub(" x ", " xbi ", s)
    s = gsub("([0-9])x([0-9])", "\\1 xbi \\2", s)
    s = gsub("([0-9])x", "\\1 xbi ", s)
    s = gsub("x([0-9])", "xbi \\1 ", s)
    s = gsub("\\*", " xbi ", s)
    s = gsub(" by ", " xbi ", s)
    s = gsub("([0-9])( *)\\.( *)([0-9])", "\\1.\\4", s)
    s = gsub("([0-9]+)( *)(inches|inch|in|inces|')\\.?", "\\1in. ", s)
    s = gsub("([0-9]+)( *)(foot|feet|ft|'')\\.?", "\\1ft. ", s)
    s = gsub("([0-9]+)( *)(pounds|pound|lbs|lb)\\.?", "\\1lb. ", s)
    s = gsub("([0-9]+)( *)(square|sq) ?\\.?(feet|foot|ft)\\.?", "\\1sq.ft. ", s)
    s = gsub("([0-9]+)( *)(cubic|cu) ?\\.?(feet|foot|ft)\\.?", "\\1cu.ft. ", s)
    s = gsub("([0-9]+)( *)(gallons|gallon|gal)\\.?", "\\1gal. ", s)
    s = gsub("([0-9]+)( *)(ounces|ounce|oz)\\.?", "\\1oz. ", s)
    s = gsub("([0-9]+)( *)(centimeters|cm)\\.?", "\\1cm. ", s)
    s = gsub("([0-9]+)( *)(milimeters|mm)\\.?", "\\1mm. ", s)
    s = gsub("([0-9]+)( *)(height|h)\\.?", "\\1h. ", s)
    s = gsub("([0-9]+)( *)(width|with|w)\\.?", "\\1w. ", s)
    s = gsub("([0-9]+)( *)(depth|d)\\.?", "\\1d. ", s)
    s = gsub("°", " degrees ", s)
    s = gsub("([0-9]+)( *)(degrees|degree)\\.?", "\\1deg. ", s)
    s = gsub(" v ", " volts ", s)
    s = gsub("([0-9]+)( *)(volts|volt)\\.?", "\\1volt. ", s)
    s = gsub("([0-9]+)( *)(watts|watt)\\.?", "\\1watt. ", s)
    s = gsub("([0-9]+)( *)(amperes|ampere|amps|amp)\\.?", "\\1amp. ", s)
    s = gsub("  ", " ", s)
    s = gsub(" \\. ", " ", s)
    
    ##s = (" ").join([z for z in s.split(" ") if z not in stop_w])

    return(s)
  }
  else
    return("null")
}

str_num_normalize <- function(s){
  
  s = gsub("( *)zero( *)", "0", s)
  s = gsub("( *)one( *)", "1", s)
  s = gsub("( *)two( *)", "2", s)
  s = gsub("( *)three( *)", "3", s)
  s = gsub("( *)four( *)", "4", s)
  s = gsub("( *)five( *)", "5", s)
  s = gsub("( *)six( *)", "6", s)
  s = gsub("( *)seven( *)", "7", s)
  s = gsub("( *)eight( *)", "8", s)
  s = gsub("( *)nine( *)", "9", s)
  s = gsub("( *)ten( *)", "10", s)
  
  s = gsub("( *)eleven( *)", " 11 ", s)
  s = gsub("( *)twelve( *)", " 12 ", s)
  s = gsub("( *)thirteen( *)", " 13 ", s)
  s = gsub("( *)fourteen( *)", " 14 ", s)
  s = gsub("( *)fifteen( *)", " 15 ", s)
  s = gsub("( *)sixteen( *)", " 16 ", s)
  s = gsub("( *)seventeen( *)", " 17 ", s)
  s = gsub("( *)eighteen( *)", " 18 ", s)
  s = gsub("( *)nineteen( *)", " 19 ", s)
  
  s = gsub("( *)twenty( *)([a-z])", "20 ", s)
  s = gsub("( *)twenty( *)", "2", s)
  s = gsub("( *)thirty( *)([a-z])", "30 ", s)
  s = gsub("( *)thirty( *)", "3", s)
  s = gsub("( *)forty( *)([a-z])", "40 ", s)
  s = gsub("( *)forty( *)", "4", s)
  s = gsub("( *)fifty( *)([a-z])", "50 ", s)
  s = gsub("( *)fifty( *)", "5", s)
  s = gsub("( *)sixty( *)([a-z])", "60 ", s)
  s = gsub("( *)sixty( *)", "6", s)
  s = gsub("( *)seventy( *)([a-z])", "70 ", s)
  s = gsub("( *)seventy( *)", "7", s)
  s = gsub("( *)eighty( *)([a-z])", "80 ", s)
  s = gsub("( *)eighty( *)", "8", s)
  s = gsub("( *)ninety( *)([a-z])", "90 ", s)
  s = gsub("( *)ninety( *)", "9", s)
  
  s = gsub("( *)([1-2]) *half(s*)( *)", " \\2/2 ", s)
  s = gsub("( *)half( *)|( *)(0*)( *)\\.( *)5( *)(0*)( *)", " 1/2 ", s)
  s = gsub("( *)([1-3]) *third(s*)( *)", " \\2/3 ", s)
  s = gsub("( *)third( *)|( *)(0*)( *)\\.( *)3( *)(3*)( *)", " 1/3 ", s)
  s = gsub("( *)(0*)( *)\\.( *)6( *)(6*)( *)", " 2/3 ", s)
  s = gsub("( *)([1-4]) *fourth(s*)( *)", " \\2/4 ", s)
  s = gsub("( *)fourth( *)|( *)(0*)( *)\\.( *)2( *)5( *)", " 1/4 ", s)
  s = gsub("( *)(0*)( *)\\.( *)7( *)5( *)", " 3/4 ", s)
  s = gsub("( *)([1-5]) *fifth(s*)( *)", " \\2/5 ", s)
  s = gsub("( *)fifth( *)|( *)(0*)( *)\\.( *)2( *)(0*)( *)", " 1/5 ", s)
  s = gsub("( *)(0*)( *)\\.( *)4( *)0( *)", " 2/5 ", s)
  s = gsub("( *)(0*)( *)\\.( *)6( *)0( *)", " 3/5 ", s)
  s = gsub("( *)(0*)( *)\\.( *)8( *)0( *)", " 4/5 ", s)
  s = gsub("( *)([1-6]) *sixth(s*)( *)", " \\2/6 ", s)
  s = gsub("( *)sixth( *)", " 1/6 ", s)
  
  return(s)
}

seg_words <- function(str1, str2){
  
  str2 = tolower(str2)
  str2 = gsub("[^a-z0-9./]"," ", str2)
  str2 = unique(unlist(strsplit(str2, " ")))[nchar(unique(unlist(strsplit(str2, " ")))) > 2]
  words = unlist(strsplit(tolower(str1), " "))
  s = c()
  for(word in words){
    if(nchar(word) > 3){
      s1 = c()
      s1 = append(s1, segmentit(word, str2, TRUE))
      if(length(s) > 1) s = append(s, s1[!s1 %in% c('er','ing','s','less') & nchar(s1) > 1])
      else s = append(s, word)
    }
    else s = append(s, word)
  }
  return(paste(s, collapse = " "))
}

segmentit <- function(s, txt_arr, t){
  st = s
  r = c()
  for(j in 1:nchar(s))
    for(word in txt_arr){
      s_without_last_j = paste(head(unlist(strsplit(s,"")), -j), collapse = "")
      if(word == s_without_last_j){
        #print(paste("word:",word))
        #print(paste("j:",j))
        r = append(r, s_without_last_j)
        #print(s[:-j],s[len(s)-j:])
        s = paste(unlist(strsplit(s,""))[nchar(s)-j:nchar(s)], collapse = "")
        r = append(r, segmentit(s, txt_arr, FALSE))
      }
    }
  if(t == TRUE) {
    i = nchar(paste(r, collapse = ""))
    if(i != nchar(st)) 
      append(r, paste(unlist(strsplit(st,""))[i:length(st)], collapse = ""))
  }
  return(r)
}

str_common_word <- function(str1, str2){
  words = unlist(strsplit(str1, " "))
  cnt = 0
  for(word in words)
    if(word != "") if(aregexec(word, str2, fixed = T)[[1]][1] >= 1) cnt = cnt + 1
    #if(regexpr(word, str2, fixed = T)[1] >= 1) cnt = cnt + 1
  
  return(cnt)
}

str_whole_word <- function(str1, str2, i_){
  cnt = 0
  while(i_ < nchar(str2)){
    #str_pos = regexpr(str1, substr(str2, i_, nchar(str2)), fixed = T)[1]
    str_pos = aregexec(str1, substr(str2, i_, nchar(str2)), fixed = T)[[1]][1]
    if(str_pos >= 1) i_ = i_ + str_pos - 1
    else i_ = str_pos

    if(i_ == -1)
      return(cnt)
    else
      cnt = cnt + 1
    i_ = i_ + nchar(str1)
  }
  return(cnt)
}

# Ref: http://www.r-statistics.com/2012/01/merging-two-data-frame-objects-while-preserving-the-rows-order/
# this function works just like merge, only that it adds the option to return 
# the merged data.frame ordered by x (1) or by y (2).
# This function has been updated by Mohammed to recover colmns' order.
merge.with.order <- function(x,y, ..., sort = T, keep_order){
  
  colnames <- unique(c(colnames(x), colnames(y)))
  add.id.column.to.data <- function(DATA)
  {
    data.frame(DATA, id... = seq_len(nrow(DATA)))
  }
  # add.id.column.to.data(data.frame(x = rnorm(5), x2 = rnorm(5)))
  order.by.id...and.remove.it <- function(DATA)
  {
    # gets in a data.frame with the "id..." column.  Orders by it and returns it
    if(!any(colnames(DATA)=="id...")) stop("The function order.by.id...and.remove.it only works with data.frame objects which includes the 'id...' order column")
    
    ss_r <- order(DATA$id...)
    ss_c <- colnames(DATA) != "id..."
    DATA[ss_r, ss_c]
  }
  
  order.columns <- function(DATA, colnames) DATA[,colnames]
  
  # tmp <- function(x) x==1; 1	# why we must check what to do if it is missing or not...
  # tmp()
  
  if(!missing(keep_order))
  {
    if(keep_order == 1) return(order.columns(order.by.id...and.remove.it(merge(x=add.id.column.to.data(x),y=y,..., sort = FALSE)), colnames))
    if(keep_order == 2) return(order.columns(order.by.id...and.remove.it(merge(x=x,y=add.id.column.to.data(y),..., sort = FALSE)), colnames))
    # if you didn't get "return" by now - issue a warning.
    warning("The function merge.with.order only accepts NULL/1/2 values for the keep_order variable")
  } else {return(merge(x=x,y=y,..., sort = sort))}
}

str_stem <- function(s, x=1){
  
  if(x %% 100 == 0) cat(paste0(x , " values stemmed. \n"))
  
  if(!is.na(s) && is.character(s)) {
    
    s = paste(wordStem(unlist(strsplit(s, " ")), language = "english"), collapse = " ")
    
    return(s)
  }
  else
    return("null")
}

# Ref: http://www.sumsar.net/blog/2014/12/peter-norvigs-spell-checker-in-two-lines-of-r/
str_Peter_Norvig_spell_checker <- function(sentence, source){
  
  sorted_words <- names(sort(table(strsplit(tolower(source), "[^a-z]+")), decreasing = TRUE))
  words = unlist(strsplit(sentence, " "))
  
  correct <- function(word, sorted_words) { 
    c(sorted_words[ adist(word, sorted_words) <= min(adist(word, sorted_words), 2)], word)[1] 
  }
  for(i in 1:length(words)){
    corr = correct(words[i], sorted_words)
    if(corr != "" && corr != words[i])
      words[i] = corr
  }
  return(paste(words, collapse = " "))
}

str_spell_check <- function(s, x=1){
  
  if(x %% 100 == 0) cat(paste0(x , " values checked. \n"))
  
  if(!is.na(s) && is.character(s)) {
  
    s = tolower(s)
    s = gsub("toliet", "toilet", s , fixed = T)
    s = gsub("vinal", "vinyl", s , fixed = T)
    s = gsub("vynal", "vinyl", s , fixed = T)
    s = gsub("skill", "skil", s , fixed = T)
    s = gsub("snow blower", "snowblower", s , fixed = T)   
    s = gsub("snowblowersSuperior", "snowblowers Superior", s , fixed = T)
    s = gsub("snowblowersGrounded", "snowblowers Grounded", s , fixed = T)
    s = gsub("snowblowersLong", "snowblowers Long", s , fixed = T)
    s = gsub("snow blowerr scraper blade", "snowblower scraper blade", s , fixed = T)
    s = gsub("plexigla", "plexiglass", s , fixed = T)
    s = gsub("plexiglas", "plexiglass", s , fixed = T)
    s = gsub("plexy glass", "plexiglass", s , fixed = T)
    s = gsub("plexiglassNon-acid", "plexiglass Non-acid", s , fixed = T)
    s = gsub("rustoleum", "rust-oleum", s , fixed = T)
    s = gsub("rust oleum", "rust-oleum", s , fixed = T)
    s = gsub("whirpool", "whirlpool", s , fixed = T)
    s = gsub("whirlpoolga", "whirlpool ga", s , fixed = T)
    s = gsub("whirlpoolgas stove", "whirlpool gas stove", s , fixed = T)
    s = gsub("whirlpoolstainless", "whirlpool stainless", s , fixed = T)
    
    
    s = gsub("outdoorlounge", "outdoor lounge", s , fixed = T)
    s = gsub("pricepfister", "price pfister", s , fixed = T)
    s = gsub("high boy tolet", "highboy toilet", s , fixed = T)
    s = gsub("/heaterconditioner", "/heat conditioner", s , fixed = T)
    s = gsub("base board molding boundle", "baseboard molding bundle", s , fixed = T)
    s = gsub("infloor flange", "in floor flange", s , fixed = T) # need str clean after that
    s = gsub("powertool", "power tool", s , fixed = T)
    s = gsub("frostking", "frost king", s , fixed = T)
    s = gsub("greecianmarble", "grecian marble", s , fixed = T)
    s = gsub("flatbraces", "flat braces", s , fixed = T)
    s = gsub("cordlessrotary hammerss", "cordless rotary hammers", s , fixed = T)
    s = gsub("pedelal", "pedestal", s , fixed = T)
    s = gsub("wattsolar", "watt solar", s , fixed = T)
    s = gsub("buikids", "buy kids", s , fixed = T)
    s = gsub("land scaping timbers", "landscaping timbers", s , fixed = T)
    s = gsub("dropcloth", "drop cloth", s , fixed = T)
    s = gsub("everblit", "everbilt", s , fixed = T)
    s = gsub("bath rom", "bathroom", s , fixed = T)
    s = gsub("alumanam", "aluminum", s , fixed = T)
    s = gsub("btuair", "btu air", s , fixed = T)
    s = gsub("christmass", "christmas", s , fixed = T)
    s = gsub("round up", "roundup", s , fixed = T)
    s = gsub("replacment", "replacement", s , fixed = T)
    s = gsub("ridiing lawnmower", "riding lawn mower", s , fixed = T)
    s = gsub("blk pipe", "black pipe", s , fixed = T)
    s = gsub("waater", "water", s , fixed = T)
    s = gsub("hardiboard", "hardie board", s , fixed = T)
    s = gsub("craft an lawn mower", "craftsman lawn mower", s , fixed = T)
    s = gsub("traffic master porcelin", "trafficmaster porcelain", s , fixed = T)
    s = gsub("chainlink", "chain link", s , fixed = T)
    s = gsub("book shelve", "bookshelf", s , fixed = T)
    s = gsub("washerparts", "washer parts", s , fixed = T)
    s = gsub("wht", "white", s , fixed = T)
    s = gsub("topmetal", "top metal", s , fixed = T)
    s = gsub("weewacker", "weed wacker", s , fixed = T)
    s = gsub("thewall", "the wall", s , fixed = T)
    s = gsub("4x4treaded", "4x6 treated", s , fixed = T) #***********
    s = gsub("preature", "pressure", s , fixed = T)
    s = gsub("fiber glass pip", "fiberglass pipe", s , fixed = T)
    s = gsub("hotwater", "hot water", s , fixed = T)
    s = gsub("14heightx24withx15depth", "14 height x 24 width x 15 depth", s , fixed = T)
    s = gsub("ventenatural", "vented natural", s , fixed = T)
    s = gsub("vaporbarrier", "vapor barrier, crawl space", s , fixed = T)
    s = gsub("gazhose", "gas hose", s , fixed = T)
    s = gsub("fireplacewater", "electric fireplace water heaters", s , fixed = T)
    s = gsub("frenchdoor", "french door", s , fixed = T)
    s = gsub("micro wave", "microwave", s , fixed = T)
    s = gsub("bathroon", "bathroom", s , fixed = T)
    s = gsub("vynik", "vinyl", s , fixed = T)
    s = gsub("aircondiioner", "conditioner", s , fixed = T)
    s = gsub("pivotangle", "pivot angle", s , fixed = T)
    s = gsub("armer max", "armormax", s , fixed = T)
    s = gsub("edgetape", "edge tape", s , fixed = T)
    s = gsub("aluminumm", "aluminum", s , fixed = T)
    s = gsub("wheel barrel", "wheelbarrow", s , fixed = T)
    s = gsub("rachet scret drivers", "ratchet screwdrivers", s , fixed = T)
    s = gsub("scree doorsscreen", "screen doors screen", s , fixed = T)
    s = gsub("flurorescent", "fluorescent", s , fixed = T)
    s = gsub("inove", "in love", s , fixed = T)
    s = gsub("perhung", "prehung", s , fixed = T)
    s = gsub("si k", "sink", s , fixed = T)
    s = gsub("job max attatchmens", "jobmax attachments", s , fixed = T)
    s = gsub("ftawning", "ft awning", s , fixed = T)
    s = gsub("versabon", "versabond", s , fixed = T)
    s = gsub("towbehind", "tow behind", s , fixed = T)
    s = gsub("underthe", "under the", s , fixed = T)
    s = gsub("gasnstove", "gas stove", s , fixed = T)
    s = gsub("flourescent", "fluorescent", s , fixed = T)
    s = gsub("residental", "residential", s , fixed = T)
    s = gsub("ree bar", "rebar", s , fixed = T)
    s = gsub("hot point", "hotpoint", s , fixed = T)
    s = gsub("filer", "filter", s , fixed = T)
    s = gsub("bright coach metallic", "bright coat metallic", s , fixed = T)
    
    s = gsub("dish washer", "dishwasher", s , fixed = T)
    s = gsub("flour sent", "fluorescent", s , fixed = T)
    s = gsub("kitchen aide", "kitchenaid", s , fixed = T)
    s = gsub("florisant", "fluorescent", s , fixed = T)
    s = gsub("bathtubes", "bathtubs", s , fixed = T)
    s = gsub("galvinized poles 20long", "galvanized poles 20 long", s , fixed = T)
    s = gsub("back flow", "backflow", s , fixed = T)
    s = gsub("prenter", "preventer", s , fixed = T)
    s = gsub("condiioner", "conditioner", s , fixed = T)
    s = gsub("windowair", "window air", s , fixed = T)
    s = gsub("topmount", "top mount", s , fixed = T)
    s = gsub("wallmount", "wall mounted", s , fixed = T)
    s = gsub("circuline", "circline", s , fixed = T)
    s = gsub("airconditioner", "air conditioner", s , fixed = T)
    s = gsub("aircondition", "air conditioner", s , fixed = T)
    s = gsub("tolet", "toilet", s , fixed = T)
    s = gsub("threshhold", "threshold", s , fixed = T)
    s = gsub("charbroil", "char broil", s , fixed = T)
    s = gsub("franco", "fernco", s , fixed = T)
    s = gsub("cuppling", "coupling", s , fixed = T)
    s = gsub("beveragecooler", "beverage cooler", s , fixed = T)
    s = gsub("anderson", "andersen", s , fixed = T)
    s = gsub("seriesimpact", "series impact", s , fixed = T)
    s = gsub("extertal", "external", s , fixed = T)
    s = gsub("sealparts", "seal parts", s , fixed = T)
    s = gsub("sno", "snow", s , fixed = T)
    s = gsub("light s", "lights", s , fixed = T)
    s = gsub("mobilehome", "mobile home", s , fixed = T)
    s = gsub("sensoroutdoor", "sensor outdoor", s , fixed = T)
    s = gsub("outdoorstorage", "outdoor storage", s , fixed = T)
    s = gsub("aluminun", "aluminum", s , fixed = T)
    s = gsub("inchbrasswalltube", "inch brass wall tube", s , fixed = T)
    s = gsub("ezup canopie", "ez up canopy", s , fixed = T)
    s = gsub("batteryfor", "battery for", s , fixed = T)
    s = gsub("electic", "electric", s , fixed = T)
    s = gsub("quarteround", "quarter round", s , fixed = T)
    s = gsub("drillimpact", "drill impact", s , fixed = T)
    
    s = gsub("malbu replacement  led light bubles", "malibu replacement led light bulbs", s , fixed = T)
    s = gsub("refrigerator frenchdoor", "refrigerator french door", s , fixed = T)
    s = gsub("picture haning kitpicture hanging kit", "picture hanging kit picture hanging kit", s , fixed = T)
    s = gsub("bathroom vanity cabinetwithouttops", "bathroom vanity cabinets without tops", s , fixed = T)
    s = gsub("chain saw eletric", "chainsaw electric", s , fixed = T)
    s = gsub("vanity in mahogany  mirros", "vanity in mahogany mirrors", s , fixed = T)
    s = gsub("engineered wood floorcleaners", "engineered wood floor cleaners", s , fixed = T)
    s = gsub("942196brinkmann 2 burner", "942196 brinkmann 2 burner", s , fixed = T)
    s = gsub("3 x3 marle tile", "3x3 marble tile", s , fixed = T)
    s = gsub("22 mm impact ocket", "22mm impact socket", s , fixed = T)
    s = gsub("prelit tree mutli", "pre lit tree multi", s , fixed = T)
    s = gsub("hazardous locationlight fixture globe", "hazardous location light fixture globe", s , fixed = T)
    s = gsub("thresh hold", "threshold", s , fixed = T)
    s = gsub("solar  powerd lights", "solar powered lights", s , fixed = T)
    s = gsub("24 white walloven", "24 white wall oven", s , fixed = T)
    s = gsub("kitchen aide mixer", "kitchenaid mixer", s , fixed = T)
    s = gsub("come along and chaincome along and chain", "come along and chain come along and chain", s , fixed = T)
    s = gsub("wall paper bprder", "wallpaper border", s , fixed = T)
    s = gsub("ironboard built in", "iron board built in", s , fixed = T)
    s = gsub("led shoplightmakita light", "led shop light makita light", s , fixed = T)
    s = gsub("bath tub shower repair lit", "bathtub shower repair kit", s , fixed = T)
    s = gsub("outlet wallplate with cover", "outlet wall plate with cover", s , fixed = T)
    s = gsub("tuband tile latex caulk", "tub and tile latex caulk", s , fixed = T)
    s = gsub("hallogen bulb  flood", "halogen bulb flood", s , fixed = T)
    s = gsub("cellular shade 23.75x37", "cellular shade 23.75x 37", s , fixed = T)
    s = gsub("wyndham vanities with no tops", "wyndham vanities without tops", s , fixed = T)
    s = gsub("wall mountreading light", "wall mount reading light", s , fixed = T)
    s = gsub("chome  framed mirror", "chrome framed mirror", s , fixed = T)
    s = gsub("b onnet", "bonnet", s , fixed = T)
    s = gsub("old style nailshand forgednails", "old style nails hand forged nails", s , fixed = T)
    s = gsub("grohe essencekitchen faucet", "grohe essence kitchen faucet", s , fixed = T)
    s = gsub("48 inchled tube", "48 inch led tube", s , fixed = T)
    s = gsub("elecric screw driver batteries", "electric screwdriver batteries", s , fixed = T)
    s = gsub("mobilehome wall paint", "mobile home wall paint", s , fixed = T)
    s = gsub("16x16x60boxes for moving", "16x16x60 boxes for moving", s , fixed = T)
    s = gsub("bathtubdoor towel racks", "bathtub door towel racks", s , fixed = T)
    s = gsub("4inch ligh junction box", "4 inch light junction box", s , fixed = T)
    s = gsub("26 in woodsaddle stool", "26 in wood saddle stool", s , fixed = T)
    s = gsub("thinset morter", "thin set mortar", s , fixed = T)
    s = gsub("flourescent g25 60watt", "fluorescent g25 60 watt", s , fixed = T)
    s = gsub("23' biview surface mount med cab chestnut", "23' bi view surface mount med cab chestnut", s , fixed = T)
    s = gsub("french pation doors with sidepanels", "french patio doors with side panels", s , fixed = T)
    s = gsub("black out doors spray paint", "black outdoor spray paint", s , fixed = T)
    s = gsub("outdoor unskid tiles", "outdoor non skid tiles", s , fixed = T)
    s = gsub("6 round headlag bolt", "6 round head lag bolt", s , fixed = T)
    s = gsub("75 qrt cooler  with wheels", "75 quart cooler with wheels", s , fixed = T)
    s = gsub("1 1/4 pvcsch 80", "1 1/4 pvc sch 80", s , fixed = T)
    s = gsub("askley electric  fireplace", "ashley electric fireplace", s , fixed = T)
    s = gsub("100 amp to 200a lit", "100 amp to 200 a lot", s , fixed = T)
    s = gsub("gren house kits", "greenhouse kits", s , fixed = T)
    s = gsub("5000 btu aircondition", "5000 btu air conditioner", s , fixed = T)
    s = gsub("kitchen aide dishwasher", "kitchenaid dishwasher", s , fixed = T)
    s = gsub("10guage copper wire 3 stand", "10 gauge copper wire 3 stand", s , fixed = T)
    s = gsub("dwaft  outside plants", "dwarf outside plants", s , fixed = T)
    s = gsub("tilebath walls small", "tile bath walls small", s , fixed = T)
    s = gsub("2 ton aircondition", "2 ton air conditioner", s , fixed = T)
    s = gsub("60x65shower doors", "60x65 shower doors", s , fixed = T)
    s = gsub("trigger makita skillsaw", "trigger makita skil saw", s , fixed = T)
    s = gsub("wall beveled framelessmirror", "wall beveled frameless mirror", s , fixed = T)
    s = gsub("slidein range bisque", "slide in range bisque", s , fixed = T)
    s = gsub("byfold hinges", "bi fold hinges", s , fixed = T)
    s = gsub("terra cota quarry stones", "terracotta quarry stones", s , fixed = T)
    s = gsub("wall paper  murial glue", "wallpaper mural glue", s , fixed = T)
    s = gsub("curtains non black out", "curtains not blackout", s , fixed = T)
    s = gsub("black and deckerbattery pack", "black and decker battery pack", s , fixed = T)
    s = gsub("lampost motion detector", "lamp post motion detector", s , fixed = T)
    s = gsub("cool  tube lgts", "cool tube lights", s , fixed = T)
    s = gsub("wheeld  trimmer", "wheeled trimmer", s , fixed = T)
    s = gsub("cerrowire 18 gauge", "cerro wire 18 gauge", s , fixed = T)
    s = gsub("wirlpool counterdepth side by side refrigrator", "whirlpool counter depth side by side refrigerator", s , fixed = T)
    s = gsub("gtxworks trimmer spools", "gt worx trimmer spools", s , fixed = T)
    s = gsub("weatherproof boom box", "waterproof boombox", s , fixed = T)
    s = gsub("cerowire 12 gauge", "cerro wire 12 gauge", s , fixed = T)
    s = gsub("1x6 toungh  groove", "1x6 tongue groove", s , fixed = T)
    s = gsub("1x4 pre primed mfd trim", "1 x 4 pre primed mdf trim", s , fixed = T)
    s = gsub("alltyp of fences", "all type of fences", s , fixed = T)
    s = gsub("whitesilicone", "white silicone", s , fixed = T)
    s = gsub("5 1/4 deckboard", "5 1/4 deck board", s , fixed = T)
    s = gsub("bathroom  plummbing", "bathroom plumbing", s , fixed = T)
    s = gsub("spray metallicpaint", "spray metallic paint", s , fixed = T)
    s = gsub("1/2  conduet", "1/2 conduit", s , fixed = T)
    s = gsub("4x7 ruggs", "4 x 7 rugs", s , fixed = T)
    s = gsub("wood paint with primerin blue", "wood paint with primer in blue", s , fixed = T)
    s = gsub("berhr  solid 213 deep", "behr solid 213 deep", s , fixed = T)
    s = gsub("driveway m arkers", "driveway markers", s , fixed = T)
    s = gsub("multinozzle spray painting", "multi nozzle spray painting", s , fixed = T)
    s = gsub("1/2x1/2 quater round", "1/2 x 1/2 quarter round", s , fixed = T)
    s = gsub("proclean concentrated drain cleaner", "pro clean concentrated drain cleaner", s , fixed = T)
    s = gsub("ridgid       powerwasher  parts", "ridgid power washer parts", s , fixed = T)
    s = gsub("brick web thin brick flats", "brickweb thin brick flats", s , fixed = T)
    s = gsub("whiteled tree", "white led tree", s , fixed = T)
    s = gsub("water proof mc connecter", "waterproof dc connector", s , fixed = T)
    s = gsub("odl 6' x 6'retractable screens", "odl 6' x 6 retractable screens", s , fixed = T)
    s = gsub("scikkens  stain", "sikkens stain", s , fixed = T)
    s = gsub("flourecent  light plastic covers", "fluorescent light plastic covers", s , fixed = T)
    s = gsub("splitbolt connector", "split bolt connector", s , fixed = T)
    s = gsub("24 inflex gas line", "24 in flex gas line", s , fixed = T)
    s = gsub("sanding machinehardwood floors", "sanding machine hardwood floors", s , fixed = T)
    s = gsub("disposal rim and stopperkohler", "disposal rim and stopper kohler", s , fixed = T)
    s = gsub("exterior pipeinsulation", "exterior pipe insulation", s , fixed = T)
    s = gsub("warm espresso bamboo quarteround", "warm espresso bamboo quarter round", s , fixed = T)
    s = gsub("woodrx ultra natural", "wood rx ultra natural", s , fixed = T)
    s = gsub("phillips bugle-head finethread sharp", "phillips bugle-head fine thread sharp", s , fixed = T)
    s = gsub("rust oleum dark hunter green spray enamel paint", "rustoleum dark hunter green spray enamel paint", s , fixed = T)
    s = gsub("bifold doorsfold plantation", "bi fold doors fold plantation", s , fixed = T)
    s = gsub("our door receptacles", "outdoor receptacles", s , fixed = T)
    s = gsub("liquid bi fuels", "liquid biofuels", s , fixed = T)
    s = gsub("ceramic tile  tooth brush and  soap holder", "ceramic tile toothbrush and soap holder", s , fixed = T)
    s = gsub("eyebolt brass", "eye bolt brass", s , fixed = T)
    s = gsub("terracotta exteriorpaint", "terracotta exterior paint", s , fixed = T)
    s = gsub("manuel venting sky light", "manual venting skylight", s , fixed = T)
    s = gsub("vanitiy top back splach", "vanity top backsplash", s , fixed = T)
    s = gsub("large yellow screw inground anchors", "large yellow screw in ground anchors", s , fixed = T)
    s = gsub("zurn hot short stemcartridge", "zurn hot short stem cartridge", s , fixed = T)
    s = gsub("the  govenore", "the governor", s , fixed = T)
    s = gsub("round plastic  tablrs", "round plastic tables", s , fixed = T)
    s = gsub("over ran", "overran", s , fixed = T)
    s = gsub("brushed stainless cabin ate hardware", "brushed stainless cabinet hardware", s , fixed = T)
    s = gsub("fork lift strps", "forklift straps", s , fixed = T)
    s = gsub("faux diamondplate", "faux diamond plate", s , fixed = T)
    s = gsub("ce tech coaxial cablenail in clips", "ce tech coaxial cable nail in clips", s , fixed = T)
    s = gsub("wood fuelpellets", "wood fuel pellets", s , fixed = T)
    s = gsub("10  roll up outside blinds", "10 roll up outdoor blinds", s , fixed = T)
    s = gsub("faucetskitchen", "faucets kitchen", s , fixed = T)
    s = gsub("undercounter lighs", "under counter lights", s , fixed = T)
    s = gsub("presusre treated  post", "pressure treated post", s , fixed = T)
    s = gsub("alumium fence 6 ft 6ft", "aluminum fence 6 ft 6 ft", s , fixed = T)
    s = gsub("93 inch widecellular shades", "93 inch wide cellular shades", s , fixed = T)
    s = gsub("aromaticeatern red cedar planking", "aromatic eastern red cedar planking", s , fixed = T)
    s = gsub("black and decker hobby crafter", "black and decker hobbycrafter", s , fixed = T)
    s = gsub("squar flushmount lights", "square flush mount lights", s , fixed = T)
    s = gsub("25ft huskt tape", "25 ft husky tape", s , fixed = T)
    s = gsub("kholerhighland white toilet", "kohler highline white toilet", s , fixed = T)
    s = gsub("power cordclass 2 power model xy_2900600_u", "power cord class 2 power model xy_2900600_u", s , fixed = T)
    s = gsub("exhaustless portable airconditioner", "exhaustless portable air conditioner", s , fixed = T)
    s = gsub("portable aircondition", "portable air conditioner", s , fixed = T)
    s = gsub("hole angel  jig", "hole angle jig", s , fixed = T)
    s = gsub("samsungelectric ranges", "samsung electric ranges", s , fixed = T)
    s = gsub("atic  fans with lubers", "attic fans with louvers", s , fixed = T)
    s = gsub("hampton bay out door celing fan", "hampton bay outdoor ceiling fan", s , fixed = T)
    s = gsub("out  door celing fan", "outdoor ceiling fan", s , fixed = T)
    s = gsub("doors for mobilhomes", "doors for mobile homes", s , fixed = T)
    s = gsub("hardi  board smooth", "hardie board smooth", s , fixed = T)
    s = gsub("galvanisedround fire pit ring", "galvanized round fire pit ring", s , fixed = T)
    s = gsub("electrichot water heaters residential", "electric hot water heaters residential", s , fixed = T)
    s = gsub("undercabinet ligghts", "under cabinet lights", s , fixed = T)
    s = gsub("martha stewartcabinet pull", "martha stewart cabinet pull", s , fixed = T)
    s = gsub("Allure mellowood flooring", "Allure mellow wood flooring", s , fixed = T)
    s = gsub("allure vinyl tilecordoba", "allure vinyl tile cordoba", s , fixed = T)
    s = gsub("powerwasher hose", "power washer hose", s , fixed = T)
    s = gsub("back yard weather forecasteer", "backyard weather forecaster", s , fixed = T)
    s = gsub("hardi trim", "hardietrim", s , fixed = T)
    s = gsub("powervent water heater", "power vent water heater", s , fixed = T)
    s = gsub("anderson replacement double hung window 34.5x36.5", "andersen replacement double hung window 34.5x 36.5", s , fixed = T)
    s = gsub("2x6 treted  8ft long", "2x6 treated 8ft long", s , fixed = T)
    s = gsub("wheel borrow", "wheelbarrow", s , fixed = T)
    s = gsub("hampton bay cabinetscornor cabinetupper", "hampton bay cabinets corner cabinet upper", s , fixed = T)
    s = gsub("sheeet rock mud", "sheetrock mud", s , fixed = T)
    s = gsub("counterdepth fridge", "counter depth fridge", s , fixed = T)
    s = gsub("whirlpool  french door frig 30 wide", "whirlpool french door fridge 30 wide", s , fixed = T)
    s = gsub("doors interiorwith door jams", "doors interior with door jams", s , fixed = T)
    s = gsub("residentialsteel door and frame", "residential steel door and frame", s , fixed = T)
    s = gsub("30 gar builtin ranges", "30 gas built in ranges", s , fixed = T)
    s = gsub("water proofing shower membrame", "waterproofing shower membrane", s , fixed = T)
    s = gsub("vinylcorner boards 4 inch", "vinyl corner boards 4 inch", s , fixed = T)
    s = gsub("nonadhesive vinyl flooring", "non adhesive vinyl flooring", s , fixed = T)
    s = gsub("5/8   floring plywood weatherproof", "5/8 flooring plywood weatherproof", s , fixed = T)
    s = gsub("14 awgsoilid wire", "14 awg solid wire", s , fixed = T)
    s = gsub("nailer  tooal", "nailer tool", s , fixed = T)
    s = gsub("weed  barier", "weed barrier", s , fixed = T)
    s = gsub("joint compund light weight", "joint compound lightweight", s , fixed = T)
    s = gsub("manual for airens lawnmower", "manual for ariens lawn mower", s , fixed = T)
    s = gsub("moen banbury 24 in. doubletowel bar", "moen banbury 24 in. double towel bar", s , fixed = T)
    s = gsub("extension  springes", "extension springs", s , fixed = T)
    s = gsub("glacier bay delmare expresso wall mirror", "glacier bay del mar espresso wall mirror", s , fixed = T)
    s = gsub("kitchen aid refrigirator light bulb,", "kitchenaid refrigerator light bulb,", s , fixed = T)
    s = gsub("water proff board", "waterproof board", s , fixed = T)
    s = gsub("12' firetreat 2x4", "12' fire treated 2x4", s , fixed = T)
    s = gsub("american-standarfairfield elongated one-piece 1.6 gpf toilet", "american-standard fairfield elongated one-piece 1.6 gpf toilet", s , fixed = T)
    s = gsub("hampton baysolar bird lights", "hampton bay solar bird lights", s , fixed = T)
    s = gsub("surfacemount kitchen sink", "surface mount kitchen sink", s , fixed = T)
    s = gsub("rigid wet nozzelsqueegee", "ridgid wet nozzle squeegee", s , fixed = T)
    s = gsub("1/2'  extirior plywood", "1/2' exterior plywood", s , fixed = T)
    s = gsub("micro fibe", "microfiber", s , fixed = T)
    s = gsub("electric lawn mowerectrical", "electric lawn mower electrical", s , fixed = T)
    s = gsub("closet clothes rackclosetmaid", "closet clothes rack closetmaid", s , fixed = T)
    s = gsub("soild core flush pre hung door", "solid core flush prehung door", s , fixed = T)
    s = gsub("freesstanding", "free standing", s , fixed = T)
    s = gsub("20x8 storge shed", "20 x 8 storage shed", s , fixed = T)
    s = gsub("swamp  oolers", "swamp coolers", s , fixed = T)
    s = gsub("built in convectionoven", "built in convection oven", s , fixed = T)
    s = gsub("landscape  wateting", "landscape watering", s , fixed = T)
    s = gsub("sockets for  fluorescence fixtres", "sockets for fluorescent fixtures", s , fixed = T)
    s = gsub("woodceramic floor tile", "wood ceramic floor tile", s , fixed = T)
    s = gsub("portercable 6 gal", "porter cable 6 gal", s , fixed = T)
    s = gsub("window ac/hehat  units", "window ac/heat units", s , fixed = T)
    s = gsub("garage bicyclestorage", "garage bicycle storage", s , fixed = T)
    s = gsub("window airconditionerwith heaters", "window air conditioners with heaters", s , fixed = T)
    s = gsub("whitecomposite fascia board", "white composite fascia board", s , fixed = T)
    s = gsub("underhood range fan", "under hood range fan", s , fixed = T)
    s = gsub("price pfister  trevisa", "price pfister treviso", s , fixed = T)
    s = gsub("buth tub faucet", "bathtub faucet", s , fixed = T)
    s = gsub("ge spring water heater", "geospring water heater", s , fixed = T)
    s = gsub("dim able balafon flood light", "dimmable balafon flood light", s , fixed = T)
    s = gsub("phone  spliter", "phone splitter", s , fixed = T)
    s = gsub("403esprit 2x4 ceing tile", "403 esprit 2x4 ceiling tile", s , fixed = T)
    s = gsub("12 v landscaping ligtening fixture", "12v landscape lighting fixture", s , fixed = T)
    s = gsub("behr white external semigloss paint", "behr white exterior semi gloss paint", s , fixed = T)
    s = gsub("arearugs and mats", "area rugs and mats", s , fixed = T)
    s = gsub("9'  plna replament blade", "9' plane replacement blade", s , fixed = T)
    s = gsub("saw zall blades", "sawzall blades", s , fixed = T)
    s = gsub("barn doorhinges", "barn door hinges", s , fixed = T)
    s = gsub("lampsade pendent light", "lamp shade pendant light", s , fixed = T)
    s = gsub("bathtub faucethandle replacement parts", "bathtub faucet handle replacement parts", s , fixed = T)
    s = gsub("prelit spiral trees", "pre lit spiral trees", s , fixed = T)
    s = gsub("solar out doors post lights", "solar outdoor post lights", s , fixed = T)
    s = gsub("rostoluem  spray paint", "rustoleum spray paint", s , fixed = T)
    s = gsub("white carrara herring bome", "white carrara herringbone", s , fixed = T)
    s = gsub("charbroil classic", "char broil classic", s , fixed = T)
    s = gsub("14 electric concrete saw with vc-u dch300", "14 electric concrete saw with vac-u dch 300", s , fixed = T)
    s = gsub("fin heating  tubeing", "fin heating tubing", s , fixed = T)
    s = gsub("4 x 4 pos cap", "4x4 post cap", s , fixed = T)
    s = gsub("shower dooroil rubbed bronze", "shower door oil rubbed bronze", s , fixed = T)
    s = gsub("kitchen aid architecs series 11", "kitchenaid architect series 11", s , fixed = T)
    s = gsub("4in drain gratewhite", "4in drain grate white", s , fixed = T)
    s = gsub("vinylcove base", "vinyl cove base", s , fixed = T)
    s = gsub("b10  led bub", "b10 led bulb", s , fixed = T)
    s = gsub("cub cadetcordless hedge trimmer", "cub cadet cordless hedge trimmer", s , fixed = T)
    s = gsub("on off valvefor tub faucet", "on off valve for tub faucet", s , fixed = T)
    s = gsub("hanging worklight fixtures ceiling", "hanging work light fixtures ceiling", s , fixed = T)
    s = gsub("washer dryer folding worksurface", "washer dryer folding work surface", s , fixed = T)
    s = gsub("door floor plate  slideing doors", "door floor plate sliding doors", s , fixed = T)
    s = gsub("12 ft john boat", "12ft jon boat", s , fixed = T)
    s = gsub("ego   hainsaw", "ego chainsaw", s , fixed = T)
    s = gsub("pullbehind fertilizer spreader", "pull behind fertilizer spreader", s , fixed = T)
    s = gsub("el ctrical s ez", "electrical sez", s , fixed = T)
    s = gsub("blue tapeexhaust fan/light", "blue tape exhaust fan/light", s , fixed = T)
    s = gsub("led hale gin g9", "led halogen g9", s , fixed = T)
    s = gsub("lawn grass catchbag", "lawn grass catcher bag", s , fixed = T)
    s = gsub("1/4 lauwan under layment", "1/4 lauan underlayment", s , fixed = T)
    s = gsub("4 inch round bellbox cover", "4 inch round bell box cover", s , fixed = T)
    s = gsub("barn doorspring latches", "barn door spring latches", s , fixed = T)
    s = gsub("three wire hottube", "three wire hot tub", s , fixed = T)
    s = gsub("outdoor hightop dining", "outdoor high top dining", s , fixed = T)
    s = gsub("16 ftdecking boards", "16 ft decking boards", s , fixed = T)
    s = gsub("sofit vents 4x16", "soffit vents 4 x 16", s , fixed = T)
    s = gsub("plactic totes  36 inches wide", "plastic totes 36 inches wide", s , fixed = T)
    s = gsub("25 watt warmlight bulb", "25 watt warm light bulb", s , fixed = T)
    s = gsub("raised garden  ed", "raised garden bed", s , fixed = T)
    s = gsub("58.75x80 sliding glass door", "58.75x 80 sliding glass door", s , fixed = T)
    s = gsub("spectacide for lawnscarpenter ants", "spectracide for lawns carpenter ants", s , fixed = T)
    s = gsub("6' remodel can valted celing  cans", "6' remodel can vaulted ceiling cans", s , fixed = T)
    s = gsub("isunderlayment requiered for metal roof", "is underlayment required for metal roof", s , fixed = T)
    s = gsub("65 watt dim able", "65 watt dimmable", s , fixed = T)
    s = gsub("fire place accessories gas loggs", "fireplace accessories gas logs", s , fixed = T)
    s = gsub("auqatic shower & bath", "aquatic shower", s , fixed = T)
    s = gsub("amdry wallpanel", "amdry wall panel", s , fixed = T)
    s = gsub("patio  tbricks", "patio bricks", s , fixed = T)
    s = gsub("sliding door storage cabi nets", "sliding door storage cabinets", s , fixed = T)
    s = gsub("kids toilet seateat", "kids toilet seat eat", s , fixed = T)
    s = gsub("30 inchesbathroom vanity", "30 inches bathroom vanity", s , fixed = T)
    s = gsub("lowvoltage indoor accent lights", "low voltage indoor accent lights", s , fixed = T)
    s = gsub("allure golden oaksku579331", "allure golden oak sku 579331", s , fixed = T)
    s = gsub("moen grab bar securemount", "moen grab bar secure mount", s , fixed = T)
    s = gsub("bateries  9v", "batteries 9v", s , fixed = T)
    s = gsub("rollup door", "roll up door", s , fixed = T)
    s = gsub("ge gfi braker 30amp", "ge gfci breaker 30 amp", s , fixed = T)
    s = gsub("light weight coccrete", "lightweight concrete", s , fixed = T)
    s = gsub("anderson french wood patio door 400 series", "andersen frenchwood patio door 400 series", s , fixed = T)
    s = gsub("2x2 ceiling tilepantq22s", "2x2 ceiling tile paint 22s", s , fixed = T)
    s = gsub("72 inchtrack light", "72 inch track light", s , fixed = T)
    s = gsub("phillips led sparkle  light bulbs", "philips led sparkle light bulbs", s , fixed = T)
    s = gsub("36  curved showered curtain rod", "36 curved shower curtain rod", s , fixed = T)
    s = gsub("metal gringing weel  5/8", "metal grinding wheel 5/8", s , fixed = T)
    s = gsub("wetbar sink and faucet", "wet bar sink and faucet", s , fixed = T)
    s = gsub("solor power lighting  for exterior", "solar power lighting for exterior", s , fixed = T)
    s = gsub("infloor heating antifreeze", "in floor heating antifreeze", s , fixed = T)
    s = gsub("drop cieling tiles 2ft by 4 ft", "drop ceiling tiles 2ft by 4ft", s , fixed = T)
    s = gsub("apartment size ge  refrigertor stainless steel", "apartment size ge refrigerator stainless steel", s , fixed = T)
    s = gsub("briggsstraton 11 horse air filter", "briggs stratton 11 horse air filter", s , fixed = T)
    s = gsub("rock wall papper", "rock wallpaper", s , fixed = T)
    s = gsub("kohler top mont bathroom  sink", "kohler top mount bathroom sink", s , fixed = T)
    s = gsub("windowbalance", "window balance", s , fixed = T)
    s = gsub("3 4  toilet phlange", "3 4 toilet flange", s , fixed = T)
    s = gsub("7 footaluminum awning", "7 foot aluminum awning", s , fixed = T)
    s = gsub("paper lawn  tefuse bags", "paper lawn refuse bags", s , fixed = T)
    s = gsub("10 x 10 gaxebo garden house", "10x10 gazebo garden house", s , fixed = T)
    s = gsub("navarra sierra passage doorknob set", "navarra sierra passage door knob set", s , fixed = T)
    s = gsub("counter and appliance gaperaser", "counter and appliance gap eraser", s , fixed = T)
    s = gsub("porta cool", "portacool", s , fixed = T)
    s = gsub("florsent  replacement diffuser", "fluorescent replacement diffuser", s , fixed = T)
    s = gsub("water proofing connector", "waterproof connector", s , fixed = T)
    s = gsub("whirl pool water heater pilot", "whirlpool water heater pilot", s , fixed = T)
    s = gsub("32 inchvinyl screen doors", "32 inch vinyl screen doors", s , fixed = T)
    s = gsub("hamptonbay shaker cabinets wall", "hampton bay shaker cabinets wall", s , fixed = T)
    s = gsub("weekender powerwasher extension arms", "weekender power washer extension arms", s , fixed = T)
    s = gsub("relief valve for  rudd hot water heater", "relief valve for ruud hot water heater", s , fixed = T)
    s = gsub("ceiling     light brackt", "ceiling light bracket", s , fixed = T)
    s = gsub("bath room sink accecories", "bathroom sink accessories", s , fixed = T)
    s = gsub("screw driver 10 iches", "screwdriver 10 inches", s , fixed = T)
    s = gsub("capacitor for quaterhorse motor 110 volts", "capacitor for quarter horse motor 110 volts", s , fixed = T)
    s = gsub("is item at homedop", "is item at home depot", s , fixed = T)
    s = gsub("in the ground rodiron plant hanger", "in the ground rod iron plant hanger", s , fixed = T)
    s = gsub("stainless steele  screws", "stainless steel screws", s , fixed = T)
    s = gsub("upsidedowncan marker paint", "upside down can marker paint", s , fixed = T)
    s = gsub("asb shower  with curtian", "asb shower with curtain", s , fixed = T)
    s = gsub("ptouch labeling tape", "p touch labeling tape", s , fixed = T)
    s = gsub("backyard xs capes", "backyard xscapes", s , fixed = T)
    s = gsub("john deere d100 sereissnow blade", "john deere d100 series snow blade", s , fixed = T)
    s = gsub("brownbrick wallpaper", "brown brick wallpaper", s , fixed = T)
    s = gsub("wg307work  jaw saw", "wg307 worx jawsaw", s , fixed = T)
    s = gsub("combination fan and lightwall switches", "combination fan and light wall switches", s , fixed = T)
    s = gsub("attachments for zero turn  touro", "attachments for zero turn toro", s , fixed = T)
    s = gsub("kitchenover sink lighting", "kitchen over sink lighting", s , fixed = T)
    s = gsub("lock tight pl", "loctite pl", s , fixed = T)
    s = gsub("1.4 cubit ft micro wave", "1.4 cubic ft microwave", s , fixed = T)
    s = gsub("glass tile backsp gpxtpnrf", "glass tile backsp gpx pnrf", s , fixed = T)
    s = gsub("kitchen aid processer", "kitchenaid processor", s , fixed = T)
    s = gsub("circular sawshop vac", "circular saw shop vac", s , fixed = T)
    s = gsub("phillips tuvpl-l 36", "philips tuv pl-l 36", s , fixed = T)
    s = gsub("phone linesplice connectors", "phone line splice connectors", s , fixed = T)
    s = gsub("organic leafgrow soil", "organic leaf grow soil", s , fixed = T)
    s = gsub("oilrubbed bronze 3/8in riser", "oil rubbed bronze 3/8in riser", s , fixed = T)
    s = gsub("sheeking  for log cabin", "seeking for log cabin", s , fixed = T)
    s = gsub("armstrong hardwood flooring422250z5p", "armstrong hardwood flooring 422250z5p", s , fixed = T)
    s = gsub("black postlantern", "black post lantern", s , fixed = T)
    s = gsub("dal tile 12x24 porcelaine  black tile", "daltile 12x24 porcelain black tile", s , fixed = T)
    s = gsub("spade terminalsnylon insulated", "spade terminals nylon insulated", s , fixed = T)
    s = gsub("jimmyproof lock", "jimmy proof lock", s , fixed = T)
    s = gsub("lockbox keydoor lock", "lockbox key door lock", s , fixed = T)
    s = gsub("aerp garden", "aerogarden", s , fixed = T)
    s = gsub("fi nish screws", "finish screws", s , fixed = T)
    s = gsub("metal      clothes handing carts", "metal clothes hanging carts", s , fixed = T)
    s = gsub("shopvac filter hepa", "shop vac filter hepa", s , fixed = T)
    s = gsub("f 30  flourescent light fixture", "f30 fluorescent light fixture", s , fixed = T)
    s = gsub("lamated counter tops", "laminate countertops", s , fixed = T)
    s = gsub("non programmable vertical  thermost", "non programmable vertical thermostat", s , fixed = T)
    s = gsub("glacier bay  shower catridge", "glacier bay shower cartridge", s , fixed = T)
    s = gsub("water pic shower head chrome", "waterpik shower head chrome", s , fixed = T)
    s = gsub("milwaukee noncontact tester", "milwaukee non contact tester", s , fixed = T)
    s = gsub("fatpack 18v", "fat pack 18v", s , fixed = T)
    s = gsub("bathroom kraft made", "bathroom kraftmaid", s , fixed = T)
    s = gsub("arcadia mettal  locks", "arcadia metal locks", s , fixed = T)
    s = gsub("red devil scraperreplacement bldes", "red devil scraper replacement blades", s , fixed = T)
    s = gsub("electric  hock for lift", "electric shock for lift", s , fixed = T)
    s = gsub("airfilter 20x24", "air filter 20x24", s , fixed = T)
    s = gsub("handi cap sink faucett", "handicap sink faucet", s , fixed = T)
    s = gsub("arc fault circute breaker 1pole 15 amp", "arc fault circuit breaker 1 pole 15 amp", s , fixed = T)
    s = gsub("heavy duty extensoion cordyellow only", "heavy duty extension cord yellow only", s , fixed = T)
    s = gsub("club cadet 46  belt", "cub cadet 46 belt", s , fixed = T)
    s = gsub("window air conditionerriding lawn mowers", "window air conditioner riding lawn mowers", s , fixed = T)
    s = gsub("grohsafe roughin valve 35015", "grohsafe rough in valve 35015", s , fixed = T)
    s = gsub("lightsavannah 3-light burnished ing fixtures", "light savannah 3-light burnished ing fixtures", s , fixed = T)
    s = gsub("jeldewen prairie mission door", "jeld wen prairie mission door", s , fixed = T)
    s = gsub("honey oak tmolding", "honey oak t molding", s , fixed = T)
    s = gsub("cablrail", "cable rail", s , fixed = T)
    s = gsub("metal 3 tiertrolley", "metal 3 tier trolley", s , fixed = T)
    s = gsub("pri meld flush bi fold doors", "primed flush bifold doors", s , fixed = T)
    s = gsub("shelter logic sun sahde", "shelterlogic sun shade", s , fixed = T)
    s = gsub("single knobreplacement for shower kohler", "single knob replacement for shower kohler", s , fixed = T)
    s = gsub("stickon shower wall tower", "stick on shower wall tower", s , fixed = T)
    s = gsub("work force prpane heatr", "workforce propane heater", s , fixed = T)
    s = gsub("white semigloass", "white semi gloss", s , fixed = T)
    s = gsub("prehung door fanlite", "prehung door fan lite", s , fixed = T)
    s = gsub("spalted m aple", "spalted maple", s , fixed = T)
    s = gsub("broadway collectionchrome vanity fixture", "broadway collection chrome vanity fixture", s , fixed = T)
    s = gsub("discontinuedbrown and tan area rug", "discontinued brown and tan area rug", s , fixed = T)
    s = gsub("he xl 44 range", "ge xl44 range", s , fixed = T)
    s = gsub("oil rubbed bronze airgap for dishwasher", "oil rubbed bronze air gap for dishwasher", s , fixed = T)
    s = gsub("decorative  clarance", "decorative clarence", s , fixed = T)
    s = gsub("wall mounteddrop leaf table", "wall mounted drop leaf table", s , fixed = T)
    s = gsub("wire fen c e", "wire fence", s , fixed = T)
    s = gsub("metal  urathane", "metal urethane", s , fixed = T)
    s = gsub("pond filter mediumpond filter pads", "pond filter media pond filter pads", s , fixed = T)
    s = gsub("foldin g patio doors", "folding patio doors", s , fixed = T)
    s = gsub("primeline mirror sliding doors", "prime line mirror sliding doors", s , fixed = T)
    s = gsub("deck  fasting systems", "deck fastening systems", s , fixed = T)
    s = gsub("lsnd scape trim edger", "landscape trim edger", s , fixed = T)
    
    s = gsub("thickrubber mat", "thick rubber mat", s , fixed = T)
    s = gsub("topdown bottom up shades", "top down bottom up shades", s , fixed = T)
    s = gsub("autom tic drawer lite", "automatic drawer light", s , fixed = T)
    
    return(s)
  }
  else
    return("null")
}